SERVICE_ARC: str = "_netaudio-arc._udp.local."
SERVICE_CHAN: str = "_netaudio-chan._udp.local."
SERVICE_CMC: str = "_netaudio-cmc._udp.local."
SERVICE_DBC: str = "_netaudio-dbc._udp.local."

MULTICAST_GROUP_HEARTBEAT = "224.0.0.233"
MULTICAST_GROUP_CONTROL_MONITORING = "224.0.0.231"

SERVICES = [SERVICE_ARC, SERVICE_CHAN, SERVICE_CMC, SERVICE_DBC]

FEATURE_VOLUME_UNSUPPORTED = [
    "DAI1",
    "DAI2",
    "DAO1",
    "DAO2",
    "DIAES3",
    "DIOUSB",
    "DIUSBC",
    "_86012780000a0003",
]

DEFAULT_MULTICAST_METERING_PORT = 8751
DEVICE_CONTROL_PORT: int = 8800
DEVICE_HEARTBEAT_PORT: int = 8708
DEVICE_INFO_PORT: int = 8702
DEVICE_INFO_SRC_PORT1 = 1029
DEVICE_INFO_SRC_PORT2 = 1030
DEVICE_SETTINGS_PORT: int = 8700

PORTS = [DEVICE_CONTROL_PORT, DEVICE_INFO_PORT, DEVICE_SETTINGS_PORT]

SUBSCRIPTION_STATUS_NONE = 0

REQUEST_DANTE_MODEL = 97
REQUEST_MAKE_MODEL = 193
RESPONSE_DANTE_MODEL = 96
RESPONSE_MAKE_MODEL = 192

