from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "packages/netaudio-core/include/netaudio_core.h"
RUST_SOURCE = ROOT / "packages/netaudio-core/src/ffi/mod.rs"
OUTPUT = ROOT / "packages/netaudio/src/netaudio/core/_abi.py"


def ctypes_type(declaration: str, opaque: set[str]) -> str:
    declaration = re.sub(r"\bconst\b", "", declaration).strip()
    depth = declaration.count("*")
    base = declaration.replace("*", "").strip()
    scalars = {
        "bool": "ctypes.c_bool",
        "char": "ctypes.c_char",
        "uint8_t": "ctypes.c_uint8",
        "uint16_t": "ctypes.c_uint16",
        "uint32_t": "ctypes.c_uint32",
        "uint64_t": "ctypes.c_uint64",
        "int32_t": "ctypes.c_int32",
        "uintptr_t": "ctypes.c_size_t",
        "NetaudioStatus": "ctypes.c_int",
        "void": "None",
    }

    if depth and (base in opaque or base == "void"):
        expression, depth = "ctypes.c_void_p", depth - 1
    elif depth and base == "char":
        expression, depth = "ctypes.c_char_p", depth - 1
    elif base in scalars:
        expression = scalars[base]
    else:
        raise ValueError(f"unsupported C type: {declaration}")

    for _ in range(depth):
        expression = f"ctypes.POINTER({expression})"

    return expression


def generate(header: str, rust_source: str) -> str:
    header = re.sub(r"/\*.*?\*/|//[^\n]*", "", header, flags=re.DOTALL)
    opaque = set(re.findall(r"typedef struct (\w+) \w+;", header))
    prototypes = re.findall(r"^([\w *]+?)\b(netaudio_\w+)\s*\(([^;{}]*)\)\s*;", header, re.MULTILINE)
    declared = set(re.findall(r"\b(netaudio_\w+)\s*\(", header))

    if not prototypes or {name for _, name, _ in prototypes} != declared:
        raise ValueError("unsupported or missing native function declarations")

    groups = {}
    seen = set()

    for result, name, arguments in sorted(prototypes, key=lambda prototype: prototype[1]):
        if name in seen:
            raise ValueError(f"duplicate native declaration: {name}")

        seen.add(name)
        argument_types = []

        if arguments.strip() != "void":
            for argument in arguments.split(","):
                match = re.fullmatch(r"([\w *]+?)\b\w+", argument.strip())

                if match is None:
                    raise ValueError(f"unsupported C argument: {argument.strip()}")

                argument_types.append(ctypes_type(match.group(1), opaque))

        signature = ctypes_type(result, opaque), tuple(argument_types)
        groups.setdefault(signature, []).append(name)

    version = re.search(r"NETAUDIO_ABI_VERSION:\s*u32\s*=\s*(\d+)", rust_source)

    if version is None:
        raise ValueError("Rust ABI version is missing")

    constants = []

    for family in ("STATUS", "PROTOCOL", "PORT", "NOTIFICATION", "RESULT_CODE"):
        declarations = re.findall(rf"NETAUDIO_{family}_([A-Z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)", header)

        if not declarations:
            raise ValueError(f"native {family.lower()} declarations are missing")

        constants.extend(f"{family}_{name} = {int(value, 0)}" for name, value in declarations)

    lines = [
        "# Generated by scripts/generate_core_binding.py from the Rust C ABI. Do not edit.",
        "import ctypes",
        "",
        f"ABI_VERSION = {version.group(1)}",
        *constants,
        "",
        "",
        "def configure(library):",
    ]

    for (result, arguments), names in groups.items():
        if len(names) == 1:
            indent = "    "
            lines.append(f"    function = library.{names[0]}")
        else:
            indent = "        "
            lines.extend(["    for name in (", *[f'        "{name}",' for name in names], "    ):"])
            lines.append("        function = getattr(library, name)")

        argument_line = f"{indent}function.argtypes = [{', '.join(arguments)}]"

        if len(argument_line) <= 120:
            lines.append(argument_line)
        else:
            lines.append(f"{indent}function.argtypes = [")
            lines.extend(f"{indent}    {argument}," for argument in arguments)
            lines.append(f"{indent}]")

        lines.extend([f"{indent}function.restype = {result}", ""])

    lines.append("    return library")
    return "\n".join(lines) + "\n"


def check_generated(header: Path = HEADER, rust_source: Path = RUST_SOURCE, output: Path = OUTPUT) -> None:
    expected = generate(header.read_text(), rust_source.read_text())

    if not output.exists() or output.read_text() != expected:
        raise RuntimeError(f"stale ctypes declarations: run scripts/generate_core_binding.py ({output})")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate ctypes declarations from the Rust C ABI")
    parser.add_argument("--header", type=Path, default=HEADER)
    parser.add_argument("--rust-source", type=Path, default=RUST_SOURCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if args.check:
        check_generated(args.header, args.rust_source, args.output)
    else:
        args.output.write_text(generate(args.header.read_text(), args.rust_source.read_text()))


if __name__ == "__main__":
    main()
