# Generated by scripts/generate_core_binding.py from the Rust C ABI. Do not edit.
import ctypes

ABI_VERSION = 11
STATUS_OK = 0
STATUS_NULL_POINTER = 1
STATUS_INVALID_UTF8 = 2
STATUS_NAME_TOO_LONG = 3
STATUS_NAME_INVALID_HYPHEN = 4
STATUS_NAME_INVALID_CHARS = 5
STATUS_BUFFER_TOO_SMALL = 6
STATUS_INVALID_ADDRESS = 7
STATUS_IO_ERROR = 8
STATUS_TIMEOUT = 9
STATUS_MALFORMED_RESPONSE = 10
STATUS_SERIALIZATION_ERROR = 11
STATUS_SUBSCRIPTION_COUNT = 12
STATUS_INVALID_JSON = 13
STATUS_INVALID_MAC = 14
STATUS_INVALID_IP = 15
STATUS_INVALID_CHANNEL_TYPE = 16
STATUS_INVALID_KEY = 17
STATUS_INVALID_PIN = 18
STATUS_CRYPTO_ERROR = 19
STATUS_INVALID_PAGE = 20
STATUS_INVALID_SUBSCRIPTION_CHANNEL = 21
STATUS_INVALID_DEVICE_TYPE = 22
STATUS_PACKET_TOO_LARGE = 23
STATUS_INVALID_CHANNEL = 24
STATUS_INVALID_LATENCY = 25
STATUS_INVALID_SAMPLE_RATE = 26
STATUS_INVALID_ENCODING = 27
STATUS_INVALID_GAIN_LEVEL = 28
STATUS_INVALID_FLOW_SLOT = 29
STATUS_INVALID_FLOW_PROTOCOL = 30
STATUS_INVALID_SEQUENCE = 31
STATUS_UNSUPPORTED_PROTOCOL_OPERATION = 32
STATUS_INTERNAL_PANIC = 33
STATUS_UNKNOWN_KIND = 34
STATUS_INVALID_LENGTH = 35
STATUS_INVALID_DESTINATION = 36
STATUS_INVALID_FLOW_IDENTITY = 37
STATUS_INVALID_RECEIVER_MAPPING = 38
PROTOCOL_DEFAULT_ARC = 10239
PROTOCOL_ARC2729 = 10025
PROTOCOL_ARC2801 = 10241
PROTOCOL_ARC2809 = 10249
PROTOCOL_ARC280_C = 10252
PROTOCOL_ARC280_F = 10255
PROTOCOL_CMC = 4608
PROTOCOL_SETTINGS = 65535
PORT_ARC = 4440
PORT_ARC_SECONDARY = 4455
PORT_SETTINGS = 8700
PORT_INFO = 8702
PORT_HEARTBEAT = 8708
PORT_CONTROL = 8800
PORT_CONTROLLER_METERING = 8751
PORT_MULTICAST_METERING = 8752
NOTIFICATION_TOPOLOGY_CHANGE = 16
NOTIFICATION_INTERFACE_STATUS = 17
NOTIFICATION_CLOCKING_STATUS = 32
NOTIFICATION_VERSIONS_STATUS = 96
NOTIFICATION_CLEAR_CONFIG_STATUS = 120
NOTIFICATION_SAMPLE_RATE_STATUS = 128
NOTIFICATION_ENCODING_STATUS = 130
NOTIFICATION_SAMPLE_RATE_PULLUP_STATUS = 132
NOTIFICATION_DEVICE_REBOOT = 146
NOTIFICATION_MANF_VERSIONS_STATUS = 192
NOTIFICATION_ROUTING_READY = 256
NOTIFICATION_TX_CHANNEL_CHANGE = 257
NOTIFICATION_RX_CHANNEL_CHANGE = 258
NOTIFICATION_TX_LABEL_CHANGE = 259
NOTIFICATION_TX_FLOW_CHANGE = 260
NOTIFICATION_RX_FLOW_CHANGE = 261
NOTIFICATION_PROPERTY_CHANGE = 262
NOTIFICATION_ROUTING_DEVICE_CHANGE = 288
NOTIFICATION_AES67_STATUS = 4103
NOTIFICATION_CODEC_STATUS = 4107
NOTIFICATION_SETTINGS_CHANGE = 4110
RESULT_CODE_REQUEST = 0
RESULT_CODE_SUCCESS = 1
RESULT_CODE_ERROR = 34
RESULT_CODE_FRONTEND_UNAVAILABLE = 48
RESULT_CODE_MORE_PAGES = 33042


def configure(library):
    for name in (
        "netaudio_abi_version",
        "netaudio_next_panel_sequence",
    ):
        function = getattr(library, name)
        function.argtypes = []
        function.restype = ctypes.c_uint32

    for name in (
        "netaudio_analog_access",
        "netaudio_analog_level_control",
        "netaudio_audio_capability_control",
        "netaudio_audio_capability_readback",
        "netaudio_build_command",
        "netaudio_build_managed_command",
        "netaudio_build_publication",
        "netaudio_build_response",
        "netaudio_channel_audio_publication",
        "netaudio_clock_configuration_matches",
        "netaudio_clock_control_availability",
        "netaudio_clock_record_revision",
        "netaudio_clock_sources",
        "netaudio_clock_subdomain_presentation",
        "netaudio_compare_transmit_flows",
        "netaudio_configuration",
        "netaudio_connection_health_update",
        "netaudio_dapi_advance_session",
        "netaudio_dapi_advance_settings_exchange",
        "netaudio_dapi_correlate_arc_response",
        "netaudio_dapi_validate_credential",
        "netaudio_device_identity",
        "netaudio_external_subscription_readback",
        "netaudio_flow_create_preflight",
        "netaudio_flow_creation_candidate",
        "netaudio_flow_delete_preflight",
        "netaudio_flow_format_readback",
        "netaudio_flow_inventory_complete",
        "netaudio_flow_inventory_protocol",
        "netaudio_flow_topology_change",
        "netaudio_flow_verification",
        "netaudio_interface_configuration",
        "netaudio_interface_redundancy_status",
        "netaudio_latency_configuration",
        "netaudio_latency_control",
        "netaudio_managed_subscription_status",
        "netaudio_network_control_state",
        "netaudio_normalize_clock_subdomain",
        "netaudio_normalize_transmit_flow_specification",
        "netaudio_operation_availability",
        "netaudio_panel_presentation",
        "netaudio_panel_profile",
        "netaudio_panel_readback_matches",
        "netaudio_performance_capabilities",
        "netaudio_performance_completion",
        "netaudio_performance_snapshot",
        "netaudio_plan_clock_configuration",
        "netaudio_plan_external_subscription",
        "netaudio_plan_panel",
        "netaudio_plan_performance_command",
        "netaudio_plan_subscription_commands",
        "netaudio_plan_subscription_reconciliation",
        "netaudio_plan_transmit_flow_create",
        "netaudio_plan_transmit_flow_delete",
        "netaudio_receiver_self_connection_capabilities",
        "netaudio_redundancy_control",
        "netaudio_sample_rate_evidence",
        "netaudio_sample_rate_topology_impact",
        "netaudio_sap_transition",
        "netaudio_settings_capabilities",
        "netaudio_subscription_classification_for_identifier",
        "netaudio_subscription_readback",
        "netaudio_transmit_flow_specification",
        "netaudio_transmit_flow_topology",
        "netaudio_verify_interface_configuration",
        "netaudio_verify_sample_rate_topology",
        "netaudio_virtual_device_advertisements",
    ):
        function = getattr(library, name)
        function.argtypes = [
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_uint8),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ]
        function.restype = ctypes.c_int

    function = library.netaudio_arc_protocol
    function.argtypes = [
        ctypes.c_char_p,
        ctypes.c_bool,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    function = library.netaudio_client_clear_wire_captures
    function.argtypes = [ctypes.c_void_p]
    function.restype = ctypes.c_int

    for name in (
        "netaudio_client_execute",
        "netaudio_export_accept",
    ):
        function = getattr(library, name)
        function.argtypes = [
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_uint8),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ]
        function.restype = ctypes.c_int

    for name in (
        "netaudio_client_free",
        "netaudio_export_free",
        "netaudio_inventory_free",
    ):
        function = getattr(library, name)
        function.argtypes = [ctypes.c_void_p]
        function.restype = None

    function = library.netaudio_client_get_aes67_configured
    function.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_int32)]
    function.restype = ctypes.c_int

    function = library.netaudio_client_get_channel_audio_metadata_json
    function.argtypes = [
        ctypes.c_void_p,
        ctypes.c_uint16,
        ctypes.c_uint16,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    function = library.netaudio_client_get_channel_count
    function.argtypes = [
        ctypes.c_void_p,
        ctypes.POINTER(ctypes.c_uint16),
        ctypes.POINTER(ctypes.c_uint16),
        ctypes.POINTER(ctypes.c_uint16),
        ctypes.POINTER(ctypes.c_int32),
    ]
    function.restype = ctypes.c_int

    for name in (
        "netaudio_client_get_device_info_json",
        "netaudio_client_get_device_name_json",
        "netaudio_client_get_device_settings_json",
        "netaudio_client_get_property_directory_json",
        "netaudio_client_get_rx_channels_json",
        "netaudio_client_get_tx_channels_json",
        "netaudio_client_get_wire_captures_json",
        "netaudio_inventory_state",
    ):
        function = getattr(library, name)
        function.argtypes = [
            ctypes.c_void_p,
            ctypes.POINTER(ctypes.c_uint8),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ]
        function.restype = ctypes.c_int

    function = library.netaudio_client_get_rx_inventory_json
    function.argtypes = [
        ctypes.c_void_p,
        ctypes.c_uint16,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    for name in (
        "netaudio_client_lock",
        "netaudio_client_unlock",
    ):
        function = getattr(library, name)
        function.argtypes = [
            ctypes.c_void_p,
            ctypes.c_char_p,
            ctypes.POINTER(ctypes.c_uint8),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_uint8),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ]
        function.restype = ctypes.c_int

    function = library.netaudio_client_new
    function.argtypes = [
        ctypes.c_char_p,
        ctypes.c_char_p,
        ctypes.c_uint16,
        ctypes.c_uint32,
        ctypes.c_uint32,
        ctypes.POINTER(ctypes.c_void_p),
    ]
    function.restype = ctypes.c_int

    function = library.netaudio_client_request
    function.argtypes = [
        ctypes.c_void_p,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.c_uint16,
        ctypes.c_bool,
        ctypes.c_uint32,
        ctypes.c_uint64,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    function = library.netaudio_client_set_device_name
    function.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
    function.restype = ctypes.c_int

    function = library.netaudio_client_set_host_mac
    function.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_uint8)]
    function.restype = ctypes.c_int

    for name in (
        "netaudio_dapi_build_arc_request",
        "netaudio_dapi_build_settings_request",
    ):
        function = getattr(library, name)
        function.argtypes = [
            ctypes.c_uint16,
            ctypes.c_uint16,
            ctypes.POINTER(ctypes.c_uint8),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_uint8),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ]
        function.restype = ctypes.c_int

    for name in (
        "netaudio_dapi_build_authentication",
        "netaudio_dapi_build_service_acknowledgement",
    ):
        function = getattr(library, name)
        function.argtypes = [
            ctypes.POINTER(ctypes.c_uint8),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_uint8),
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_size_t),
        ]
        function.restype = ctypes.c_int

    function = library.netaudio_dapi_build_domain_initialization
    function.argtypes = [
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.c_uint16,
        ctypes.c_uint16,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    function = library.netaudio_dapi_build_identify
    function.argtypes = [
        ctypes.c_uint16,
        ctypes.c_uint16,
        ctypes.c_uint16,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    for name in (
        "netaudio_dapi_build_session_open",
        "netaudio_gain_metadata",
        "netaudio_last_error_message",
        "netaudio_metering_scale",
    ):
        function = getattr(library, name)
        function.argtypes = [ctypes.POINTER(ctypes.c_uint8), ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t)]
        function.restype = ctypes.c_int

    for name in (
        "netaudio_dapi_next_wrapper_id",
        "netaudio_next_publication_id",
    ):
        function = getattr(library, name)
        function.argtypes = [ctypes.c_uint16]
        function.restype = ctypes.c_uint16

    function = library.netaudio_export_new
    function.argtypes = [ctypes.c_char_p, ctypes.POINTER(ctypes.c_void_p)]
    function.restype = ctypes.c_int

    function = library.netaudio_flow_authoring_capabilities
    function.argtypes = [
        ctypes.c_uint16,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    function = library.netaudio_host_mac
    function.argtypes = [ctypes.POINTER(ctypes.c_uint8)]
    function.restype = ctypes.c_int

    function = library.netaudio_host_mac_for_ipv4
    function.argtypes = [ctypes.c_char_p, ctypes.POINTER(ctypes.c_uint8)]
    function.restype = ctypes.c_int

    function = library.netaudio_inventory_accept
    function.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_uint8), ctypes.c_size_t]
    function.restype = ctypes.c_int

    function = library.netaudio_inventory_new
    function.argtypes = [ctypes.c_char_p, ctypes.c_uint16, ctypes.c_size_t, ctypes.POINTER(ctypes.c_void_p)]
    function.restype = ctypes.c_int

    function = library.netaudio_lock_key_length
    function.argtypes = []
    function.restype = ctypes.c_size_t

    function = library.netaudio_lock_token
    function.argtypes = [
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    function = library.netaudio_next_message_id
    function.argtypes = []
    function.restype = ctypes.c_uint16

    function = library.netaudio_parse_page
    function.argtypes = [
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.c_uint16,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    function = library.netaudio_parse_response
    function.argtypes = [
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    for name in (
        "netaudio_status_category",
        "netaudio_status_description",
        "netaudio_status_name",
    ):
        function = getattr(library, name)
        function.argtypes = [ctypes.c_int32]
        function.restype = ctypes.c_char_p

    function = library.netaudio_subscription_status
    function.argtypes = [
        ctypes.c_uint16,
        ctypes.c_uint16,
        ctypes.c_bool,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    function = library.netaudio_transmit_flow_inventory_protocols
    function.argtypes = [
        ctypes.c_uint16,
        ctypes.c_uint16,
        ctypes.POINTER(ctypes.c_uint8),
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    function.restype = ctypes.c_int

    function = library.netaudio_validate_lock_pin
    function.argtypes = [ctypes.c_char_p]
    function.restype = ctypes.c_int

    return library
