from __future__ import annotations

from enum import IntEnum

from netaudio.dante.subscription_status import (
    default_status_entry as _builtin_status_entry,
)


SERVICE_ARC: str = "_netaudio-arc._udp.local."
SERVICE_CHAN: str = "_netaudio-chan._udp.local."
SERVICE_CMC: str = "_netaudio-cmc._udp.local."
SERVICE_DBC: str = "_netaudio-dbc._udp.local."
SERVICE_VIDEO: str = "_dantevideo._udp.local."
MEDIA_SERVICE_TYPES = frozenset({SERVICE_CHAN, SERVICE_VIDEO})

MULTICAST_GROUP_HEARTBEAT = "224.0.0.233"
MULTICAST_GROUP_CONTROL_MONITORING = "224.0.0.231"

SERVICES = [SERVICE_ARC, SERVICE_CHAN, SERVICE_CMC, SERVICE_DBC, SERVICE_VIDEO]

BLUETOOTH_MODEL_IDS = {"DIOBT"}

RESULT_CODE_LOCK_REJECTION = 0x0600
RESULT_CODE_FRONTEND_UNAVAILABLE = 0x0030

DANTE_CONTROLLER_METERING_PORT = 8751
DEFAULT_MULTICAST_METERING_PORT = 8752
DEVICE_ARC_PORT: int = 4440
DEVICE_CONTROL_PORT: int = 8800
DEVICE_HEARTBEAT_PORT: int = 8708
DEVICE_INFO_PORT: int = 8702
DEVICE_INFO_SRC_PORT1 = 1029
DEVICE_INFO_SRC_PORT2 = 1030
DEVICE_ARC_SECONDARY_PORT = 4455
DEVICE_LOCK_PORT: int = 8002
DEVICE_SETTINGS_PORT: int = 8700
MCAST_HEADER_LENGTH = 32
MESSAGE_TYPE_METERING_LEVELS = 0
PCM_ENCODING_CAPABILITY_BITS = {16: 0x0002, 24: 0x0004, 32: 0x0008}
PCM_ENCODING_OCTETS = {16: 2, 24: 3, 32: 4}

PORTS = [DEVICE_ARC_PORT, DEVICE_CONTROL_PORT, DEVICE_INFO_PORT, DEVICE_SETTINGS_PORT]

DEVICE_SETTINGS_INFO_SAMPLE_RATE = 0x8020

PROTOCOL_ID = 0x27FF
PROTOCOL_SETTINGS = 0xFFFF
PROTOCOL_CMC = 0x1200
PROTOCOL_DDP_LOCK = 0x0008
PROTOCOL_ARC_2729 = 0x2729
PROTOCOL_ARC_2801 = 0x2801
PROTOCOL_ARC_2809 = 0x2809
PROTOCOL_ARC_280F = 0x280F
MODERN_ARC_PROTOCOL_IDS = (PROTOCOL_ARC_2809, PROTOCOL_ARC_280F)
ARC_PROTOCOL_IDS = (PROTOCOL_ARC_2729, PROTOCOL_ID, PROTOCOL_ARC_2801, *MODERN_ARC_PROTOCOL_IDS)
CAPTURE_PROTOCOL_IDS = (*ARC_PROTOCOL_IDS, PROTOCOL_CMC, PROTOCOL_SETTINGS)

MODERN_ARC_MEDIA_TYPE_AUDIO = 3
MODERN_ARC_MEDIA_TYPE_VIDEO = 4
MODERN_ARC_MEDIA_TYPE_ANCILLARY = 5
MODERN_ARC_MEDIA_TYPE_LABELS = {
    MODERN_ARC_MEDIA_TYPE_AUDIO: "audio",
    MODERN_ARC_MEDIA_TYPE_VIDEO: "video",
    MODERN_ARC_MEDIA_TYPE_ANCILLARY: "ancillary",
}

PROTOCOL_NAMES = {
    PROTOCOL_CMC: "PROTOCOL_CMC",
    PROTOCOL_ARC_2729: "PROTOCOL_ARC_2729",
    PROTOCOL_ID: "PROTOCOL_ARC",
    PROTOCOL_ARC_2801: "PROTOCOL_ARC_2801",
    PROTOCOL_ARC_2809: "PROTOCOL_ARC_SETTINGS",
    PROTOCOL_ARC_280F: "PROTOCOL_ARC_280F",
    PROTOCOL_DDP_LOCK: "DDP_LOCK",
    PROTOCOL_SETTINGS: "PROTOCOL_SETTINGS",
}

PROTOCOL_LABELS = {
    PROTOCOL_CMC: "CMC",
    PROTOCOL_ARC_2729: "ARC",
    PROTOCOL_ID: "ARC",
    PROTOCOL_ARC_2801: "ARC",
    PROTOCOL_ARC_2809: "ARC",
    PROTOCOL_ARC_280F: "ARC",
    PROTOCOL_SETTINGS: "SETTINGS",
}


class ProtocolId(IntEnum):
    ARC_2809 = PROTOCOL_ARC_2809
    ARC_280F = PROTOCOL_ARC_280F
    CMC = PROTOCOL_CMC
    CONTROL = PROTOCOL_ID
    SETTINGS = PROTOCOL_SETTINGS


RESULT_CODE_ERROR = 0x0022
RESULT_CODE_REQUEST = 0x0000
RESULT_CODE_SUCCESS = 0x0001
RESULT_CODE_SUCCESS_EXTENDED = 0x8112
ARC_SUCCESS_RESULT_CODES = frozenset({RESULT_CODE_SUCCESS, RESULT_CODE_SUCCESS_EXTENDED})

RESULT_CODE_NAMES = {
    RESULT_CODE_SUCCESS: "RESULT_CODE_SUCCESS",
    RESULT_CODE_ERROR: "RESULT_CODE_ERROR",
    RESULT_CODE_SUCCESS_EXTENDED: "RESULT_CODE_SUCCESS_EXTENDED",
}

ARC_RESULT_LABELS = {
    RESULT_CODE_REQUEST: "request",
    RESULT_CODE_SUCCESS: "success",
    RESULT_CODE_ERROR: "error",
    RESULT_CODE_SUCCESS_EXTENDED: "success (paginated)",
}

OPCODE_CHANNEL_COUNT = 0x1000
OPCODE_DEVICE_NAME_SET = 0x1001
OPCODE_DEVICE_NAME = 0x1002
OPCODE_DEVICE_INFO = 0x1003
OPCODE_DEVICE_SETTINGS = 0x1100
OPCODE_DEVICE_SETTINGS_SET = 0x1101
OPCODE_TX_CHANNEL_INFO = 0x2000
OPCODE_TX_CHANNEL_NAMES = 0x2010
OPCODE_TX_CHANNEL_NAME_SET = 0x2013
OPCODE_RX_CHANNELS = 0x3000
OPCODE_RX_CHANNEL_NAME_SET = 0x3001
OPCODE_PROPERTY_DIRECTORY = 0x1102
OPCODE_SET_LATENCY = 0x1101
OPCODE_SUBSCRIPTION_ADD = 0x3010
OPCODE_SUBSCRIPTION_REMOVE = 0x3014


class ArcOpcode(IntEnum):
    CHANNEL_COUNT = OPCODE_CHANNEL_COUNT
    DEVICE_INFO = OPCODE_DEVICE_INFO
    DEVICE_NAME = OPCODE_DEVICE_NAME
    DEVICE_NAME_SET = OPCODE_DEVICE_NAME_SET
    DEVICE_SETTINGS = OPCODE_DEVICE_SETTINGS
    DEVICE_SETTINGS_SET = OPCODE_DEVICE_SETTINGS_SET
    RX_CHANNEL_NAME_SET = OPCODE_RX_CHANNEL_NAME_SET
    RX_CHANNELS = OPCODE_RX_CHANNELS
    SUBSCRIPTION_ADD = OPCODE_SUBSCRIPTION_ADD
    SUBSCRIPTION_REMOVE = OPCODE_SUBSCRIPTION_REMOVE
    TX_CHANNEL_NAME_SET = OPCODE_TX_CHANNEL_NAME_SET
    TX_CHANNEL_NAMES = OPCODE_TX_CHANNEL_NAMES
    TX_CHANNELS = OPCODE_TX_CHANNEL_INFO


BUILTIN_ARC_OPCODE_NAMES = {
    OPCODE_CHANNEL_COUNT: "channel_count",
    OPCODE_DEVICE_NAME_SET: "set_device_name",
    OPCODE_DEVICE_NAME: "device_name",
    OPCODE_DEVICE_INFO: "device_info",
    OPCODE_DEVICE_SETTINGS: "device_settings",
    OPCODE_SET_LATENCY: "set_latency",
    OPCODE_PROPERTY_DIRECTORY: "property_directory",
    OPCODE_TX_CHANNEL_INFO: "transmitter_channels",
    OPCODE_TX_CHANNEL_NAMES: "transmitter_channel_names",
    OPCODE_RX_CHANNELS: "receiver_channels",
}

BUILTIN_OPCODE_NAMES = {
    (PROTOCOL_ARC_2809, OPCODE_DEVICE_NAME_SET): "set_device_name",
    (PROTOCOL_ARC_2809, 0x2400): "transmitter_channel_status",
    (PROTOCOL_ARC_2809, 0x2600): "transmitter_flow_status",
    (PROTOCOL_ARC_2809, 0x3400): "receiver_channel_status",
    (PROTOCOL_ARC_2809, 0x3410): "subscriptions",
    (PROTOCOL_ARC_2809, 0x3600): "receiver_flow_status",
    (PROTOCOL_ARC_280F, 0x2400): "transmitter_channel_status",
    (PROTOCOL_ARC_280F, 0x2600): "transmitter_flow_status",
    (PROTOCOL_ARC_280F, 0x3400): "receiver_channel_status",
    (PROTOCOL_ARC_280F, 0x3410): "subscriptions",
    (PROTOCOL_ARC_280F, 0x3600): "receiver_flow_status",
}

DEVICE_SETTINGS_PROPERTY_NAMES = {
    0x0063: "aes67_configured",
    0x8020: "sample_rate",
    0x8060: "aes67_multicast_prefix",
    0x8204: "default_latency",
    0x8205: "configured_latency",
    0x8301: "active_latency",
    0x8302: "max_latency",
    0x8306: "min_latency",
}

CONMON_MESSAGE_NAMES = {
    0x0011: "interface_status_announcement",
    0x0013: "interface_configuration",
    0x0020: "ptp_clock_status",
    0x0021: "ptp_clock_config",
    0x0022: "unmapped_0022_status",
    0x0023: "unmapped_0023_control",
    0x0024: "unmapped_0024_status",
    0x0025: "unmapped_0025_control",
    0x0026: "unmapped_0026_status",
    0x0027: "unmapped_0027_control",
    0x0040: "unmapped_0040_status",
    0x0041: "unmapped_0041_control",
    0x0060: "board_model_publication",
    0x0061: "board_model_query",
    0x0063: "identify",
    0x0077: "clear_configuration",
    0x0078: "clear_configuration_status",
    0x0080: "sample_rate_status",
    0x0081: "sample_rate_control",
    0x0082: "encoding_status",
    0x0083: "encoding_control",
    0x0084: "sample_rate_pullup_status",
    0x0085: "sample_rate_pullup_control",
    0x0086: "unmapped_0086_status",
    0x0090: "system_reset_control",
    0x0092: "system_reset_status",
    0x00C0: "make_model_publication",
    0x00C1: "make_model_query",
    0x00E0: "unmapped_00e0_status",
    0x00E1: "unmapped_00e1_control",
    0x0100: "routing_capacity_status",
    0x0102: "unmapped_0102_status",
    0x0103: "unmapped_0103_control",
    0x0106: "unmapped_0106_status",
    0x0107: "unmapped_0107_control",
    0x01FE: "metering_data",
    0x1006: "set_aes67",
    0x1008: "lock_reset_query",
    0x1009: "lock_reset_status",
    0x100A: "gain_control",
    0x100B: "gain_status",
    0x40FE: "metering_data_extended",
    0xFF04: "conmon_export_request",
    0xFF05: "conmon_export_fragment",
}

FLOW_QUERY_PROTOCOL_IDS = (0x2729, 0x2801, *MODERN_ARC_PROTOCOL_IDS)
FLOW_CREATE_PROTOCOL_IDS = (0x2729, 0x2801)
FLOW_DELETE_PROTOCOL_IDS = (0x2729, 0x2801, PROTOCOL_ARC_2809)

OPCODE_QUERY_TX_FLOWS = 0x2200
OPCODE_CREATE_TX_FLOW = 0x2201
OPCODE_DELETE_TX_FLOW = 0x2202

OPCODE_QUERY_TX_FLOWS_2809 = 0x2600
OPCODE_CREATE_TX_FLOW_2809 = 0x2601
OPCODE_DELETE_TX_FLOW_2809 = 0x2602
OPCODE_QUERY_TRANSMITTER_CHANNEL_STATUS_2809 = 0x2400
OPCODE_QUERY_RECEIVER_CHANNEL_STATUS_2809 = 0x3400
OPCODE_QUERY_RECEIVER_FLOW_STATUS_2809 = 0x3600

FLOW_TYPE_MULTICAST = 0x0002

SUBSCRIPTION_STATUS_NONE = 0x0000

NOTIFICATION_AES67_STATUS = 4103
NOTIFICATION_CLEAR_CONFIG_STATUS = 120
NOTIFICATION_CLOCKING_STATUS = 32
NOTIFICATION_DEVICE_REBOOT = 146
NOTIFICATION_ENCODING_STATUS = 130
NOTIFICATION_GAIN_STATUS = 4107
NOTIFICATION_INTERFACE_STATUS = 17
NOTIFICATION_LATENCY_CHANGE = 262
NOTIFICATION_MANF_VERSIONS_STATUS = 192
NOTIFICATION_PROPERTY_CHANGE = 262
NOTIFICATION_ROUTING_DEVICE_CHANGE = 288
NOTIFICATION_ROUTING_READY = 256
NOTIFICATION_RX_CHANNEL_CHANGE = 258
NOTIFICATION_RX_FLOW_CHANGE = 261
NOTIFICATION_SAMPLE_RATE_PULLUP_STATUS = 132
NOTIFICATION_SAMPLE_RATE_STATUS = 128
NOTIFICATION_SETTINGS_CHANGE = 4110
NOTIFICATION_TOPOLOGY_CHANGE = 16
NOTIFICATION_TX_CHANNEL_CHANGE = 257
NOTIFICATION_TX_FLOW_CHANGE = 260
NOTIFICATION_TX_LABEL_CHANGE = 259
NOTIFICATION_VERSIONS_STATUS = 96

NOTIFICATION_NAMES = {
    NOTIFICATION_TOPOLOGY_CHANGE: "Topology Change",
    NOTIFICATION_INTERFACE_STATUS: "Interface Status",
    NOTIFICATION_CLOCKING_STATUS: "Clocking Status",
    NOTIFICATION_VERSIONS_STATUS: "Versions Status",
    NOTIFICATION_CLEAR_CONFIG_STATUS: "Clear Config Status",
    NOTIFICATION_SAMPLE_RATE_STATUS: "Sample Rate Status",
    NOTIFICATION_ENCODING_STATUS: "Encoding Status",
    NOTIFICATION_SAMPLE_RATE_PULLUP_STATUS: "Sample Rate Pull-Up Status",
    NOTIFICATION_DEVICE_REBOOT: "Device Reboot",
    NOTIFICATION_MANF_VERSIONS_STATUS: "Manufacturer Versions Status",
    NOTIFICATION_ROUTING_READY: "Routing Ready",
    NOTIFICATION_TX_CHANNEL_CHANGE: "TX Channel Change",
    NOTIFICATION_RX_CHANNEL_CHANGE: "RX Channel Change",
    NOTIFICATION_TX_LABEL_CHANGE: "TX Label Change",
    NOTIFICATION_TX_FLOW_CHANGE: "TX Flow Change",
    NOTIFICATION_RX_FLOW_CHANGE: "RX Flow Change",
    NOTIFICATION_PROPERTY_CHANGE: "Property Change",
    NOTIFICATION_ROUTING_DEVICE_CHANGE: "Routing Device Change",
    NOTIFICATION_AES67_STATUS: "AES67 Status",
    NOTIFICATION_GAIN_STATUS: "Gain Status",
    NOTIFICATION_SETTINGS_CHANGE: "Settings Change",
}

CONMON_AES67_CURRENT_NEW_OFFSET = 0x21
CONMON_CLOCK_FREQUENCY_OFFSET_PARTS_PER_BILLION_OFFSET = 0x28
CONMON_CLOCK_PORT_STATE_OFFSET = 0x48
CONMON_HEADER_LENGTH = 0x20
CONMON_MAGIC = b"Audinate"
CONMON_OPCODE_AES67_CURRENT_NEW = 0x1007
CONMON_OPCODE_BLUETOOTH_STATUS = 0x100E
CONMON_OPCODE_CLEAR_CONFIGURATION_STATUS = 0x0078
CONMON_OPCODE_DANTE_MODEL_RESPONSE = 0x0060
CONMON_OPCODE_ENCODING_STATUS = 0x0082
CONMON_OPCODE_EXPORT_FRAGMENT = 0xFF05
CONMON_OPCODE_GAIN_STATUS = 0x100B
CONMON_OPCODE_INTERFACE_STATUS = 0x0011
CONMON_OPCODE_LINK_STATUS = 0x0040
CONMON_OPCODE_LOCK_RESET_STATUS = 0x1009
CONMON_OPCODE_MAKE_MODEL_RESPONSE = 0x00C0
CONMON_OPCODE_PTP_CLOCK_STATUS = 0x0020
CONMON_OPCODE_ROUTING_CAPACITY_STATUS = NOTIFICATION_ROUTING_READY
CONMON_OPCODE_SAMPLE_RATE_PULLUP_STATUS = 0x0084
CONMON_OPCODE_SAMPLE_RATE_STATUS = 0x0080
CONMON_OPCODE_SWITCH_CONFIGURATION_STATUS = 0x0014
CONMON_PREFERRED_LEADER_OFFSET = 0x26

CLOCK_PORT_STATE_FOLLOWER = 0x0009
CLOCK_PORT_STATE_LEADER = 0x0006
CLOCK_PORT_ROLE_MAP = {
    CLOCK_PORT_STATE_LEADER: "Leader",
    CLOCK_PORT_STATE_FOLLOWER: "Follower",
}


def subscription_status_entry(code: int, receiver_status_code: int | None = None) -> dict[str, object]:
    return _builtin_status_entry(code, receiver_status_code)


def subscription_status_label(code: int, receiver_status_code: int | None = None) -> str:
    return subscription_status_entry(code, receiver_status_code)["label"]


def subscription_status_detail(code: int, receiver_status_code: int | None = None) -> str | None:
    return subscription_status_entry(code, receiver_status_code)["detail"]
