from __future__ import annotations

from netaudio.core._abi import (
    NOTIFICATION_AES67_STATUS,
    NOTIFICATION_CLEAR_CONFIG_STATUS,
    NOTIFICATION_CLOCKING_STATUS,
    NOTIFICATION_CODEC_STATUS,
    NOTIFICATION_DEVICE_REBOOT,
    NOTIFICATION_ENCODING_STATUS,
    NOTIFICATION_INTERFACE_STATUS,
    NOTIFICATION_MANF_VERSIONS_STATUS,
    NOTIFICATION_PROPERTY_CHANGE,
    NOTIFICATION_ROUTING_DEVICE_CHANGE,
    NOTIFICATION_ROUTING_READY,
    NOTIFICATION_RX_CHANNEL_CHANGE,
    NOTIFICATION_RX_FLOW_CHANGE,
    NOTIFICATION_SAMPLE_RATE_STATUS,
    NOTIFICATION_SETTINGS_CHANGE,
    NOTIFICATION_TX_CHANNEL_CHANGE,
    NOTIFICATION_TX_FLOW_CHANGE,
    NOTIFICATION_TX_LABEL_CHANGE,
    NOTIFICATION_VERSIONS_STATUS,
    PORT_ARC as DEVICE_ARC_PORT,
    PORT_ARC_SECONDARY as DEVICE_ARC_SECONDARY_PORT,
    PORT_CONTROL as DEVICE_CONTROL_PORT,
    PORT_CONTROLLER_METERING as DANTE_CONTROLLER_METERING_PORT,
    PORT_HEARTBEAT as DEVICE_HEARTBEAT_PORT,
    PORT_INFO as DEVICE_INFO_PORT,
    PORT_MULTICAST_METERING as DEFAULT_MULTICAST_METERING_PORT,
    PORT_SETTINGS as DEVICE_SETTINGS_PORT,
    PROTOCOL_ARC2729 as PROTOCOL_ARC_2729,
    PROTOCOL_ARC2801 as PROTOCOL_ARC_2801,
    PROTOCOL_ARC2809 as PROTOCOL_ARC_2809,
    PROTOCOL_ARC280_F as PROTOCOL_ARC_280F,
    PROTOCOL_CMC,
    PROTOCOL_DEFAULT_ARC as PROTOCOL_ID,
    PROTOCOL_SETTINGS,
    RESULT_CODE_REQUEST,
    RESULT_CODE_SUCCESS,
)
from netaudio.core._protocols import (
    ARC_PROTOCOL_IDS,
    CAPTURE_PROTOCOL_IDS,
    MODERN_ARC_PROTOCOL_IDS,
    PROTOCOL_LABELS,
)

__all__ = [
    "ARC_PROTOCOL_IDS",
    "CAPTURE_PROTOCOL_IDS",
    "MODERN_ARC_PROTOCOL_IDS",
    "PROTOCOL_LABELS",
    "NOTIFICATION_AES67_STATUS",
    "NOTIFICATION_CLEAR_CONFIG_STATUS",
    "NOTIFICATION_CLOCKING_STATUS",
    "NOTIFICATION_CODEC_STATUS",
    "NOTIFICATION_DEVICE_REBOOT",
    "NOTIFICATION_ENCODING_STATUS",
    "NOTIFICATION_INTERFACE_STATUS",
    "NOTIFICATION_MANF_VERSIONS_STATUS",
    "NOTIFICATION_PROPERTY_CHANGE",
    "NOTIFICATION_ROUTING_DEVICE_CHANGE",
    "NOTIFICATION_ROUTING_READY",
    "NOTIFICATION_RX_CHANNEL_CHANGE",
    "NOTIFICATION_RX_FLOW_CHANGE",
    "NOTIFICATION_SAMPLE_RATE_STATUS",
    "NOTIFICATION_SETTINGS_CHANGE",
    "NOTIFICATION_TX_CHANNEL_CHANGE",
    "NOTIFICATION_TX_FLOW_CHANGE",
    "NOTIFICATION_TX_LABEL_CHANGE",
    "NOTIFICATION_VERSIONS_STATUS",
    "DEVICE_ARC_PORT",
    "DEVICE_ARC_SECONDARY_PORT",
    "DEVICE_CONTROL_PORT",
    "DANTE_CONTROLLER_METERING_PORT",
    "DEVICE_HEARTBEAT_PORT",
    "DEVICE_INFO_PORT",
    "DEFAULT_MULTICAST_METERING_PORT",
    "DEVICE_SETTINGS_PORT",
    "PROTOCOL_ARC_2729",
    "PROTOCOL_ARC_2801",
    "PROTOCOL_ARC_2809",
    "PROTOCOL_ARC_280F",
    "PROTOCOL_CMC",
    "PROTOCOL_ID",
    "PROTOCOL_SETTINGS",
    "RESULT_CODE_REQUEST",
    "RESULT_CODE_SUCCESS",
]

SERVICE_ARC: str = "_netaudio-arc._udp.local."
SERVICE_CHAN: str = "_netaudio-chan._udp.local."
SERVICE_CMC: str = "_netaudio-cmc._udp.local."
SERVICE_DBC: str = "_netaudio-dbc._udp.local."
SERVICE_VIDEO: str = "_dantevideo._udp.local."
MEDIA_SERVICE_TYPES = frozenset({SERVICE_CHAN, SERVICE_VIDEO})

MULTICAST_GROUP_HEARTBEAT = "224.0.0.233"
MULTICAST_GROUP_CONTROL_MONITORING = "224.0.0.231"

SERVICES = [SERVICE_ARC, SERVICE_CHAN, SERVICE_CMC, SERVICE_DBC, SERVICE_VIDEO]
