use super::*;

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ConmonOpcode {
    pub opcode: Option<u16>,
}

pub fn parse_conmon_opcode(data: &[u8]) -> Option<ConmonOpcode> {
    Some(ConmonOpcode {
        opcode: Some(conmon_opcode(data)?),
    })
}

pub const CONMON_OPCODE_INTERFACE_STATUS: u16 = 0x0011;
pub const CONMON_OPCODE_SWITCH_CONFIGURATION_STATUS: u16 = 0x0014;
pub const CONMON_OPCODE_CLEAR_CONFIGURATION_STATUS: u16 = 0x0078;
pub const CONMON_OPCODE_MAKE_MODEL_RESPONSE: u16 = 0x00C0;
pub const CONMON_OPCODE_DANTE_MODEL_RESPONSE: u16 = 0x0060;
pub const CONMON_OPCODE_SAMPLE_RATE_STATUS: u16 = 0x0080;
pub const CONMON_OPCODE_UNMAPPED_0022_STATUS: u16 = 0x0022;
pub const CONMON_OPCODE_UNMAPPED_0024_STATUS: u16 = 0x0024;
pub const CONMON_OPCODE_UNMAPPED_0026_STATUS: u16 = 0x0026;
pub const CONMON_OPCODE_UNMAPPED_0040_STATUS: u16 = 0x0040;
pub const CONMON_OPCODE_UNMAPPED_0086_STATUS: u16 = 0x0086;
pub const CONMON_OPCODE_UNMAPPED_00E0_STATUS: u16 = 0x00E0;
pub const CONMON_OPCODE_UNMAPPED_0102_STATUS: u16 = 0x0102;
pub const CONMON_OPCODE_UNMAPPED_0106_STATUS: u16 = 0x0106;
pub const CONMON_OPCODE_ENCODING_STATUS: u16 = 0x0082;
pub const CONMON_OPCODE_SAMPLE_RATE_PULLUP_STATUS: u16 = 0x0084;
pub const CONMON_OPCODE_GAIN_STATUS: u16 = 0x100B;
pub const CONMON_OPCODE_AES67_CURRENT_NEW: u16 = 0x1007;
pub const CONMON_OPCODE_LOCK_RESET_STATUS: u16 = 0x1009;
pub const CONMON_OPCODE_PTP_CLOCK_STATUS: u16 = 0x0020;
pub const CONMON_OPCODE_ROUTING_CAPACITY_STATUS: u16 = 0x0100;
pub const CONMON_OPCODE_EXPORT_FRAGMENT: u16 = 0xFF05;

pub(super) const CONMON_SUPPORTED_SAMPLE_RATE_COUNT_OFFSET: usize = 0x22;
pub(super) const CONMON_CLEAR_CONFIGURATION_RECORD_IDENTIFIER_OFFSET: usize = 0x18;
pub(super) const CONMON_CLEAR_CONFIGURATION_FIRST_WORD_OFFSET: usize = 0x1C;
pub(super) const CONMON_CLEAR_CONFIGURATION_AVAILABLE_ACTIONS_MASK_OFFSET: usize = 0x20;
pub(super) const CONMON_CLEAR_CONFIGURATION_ACTION_RESULT_CODE_OFFSET: usize = 0x24;
pub(super) const CONMON_CLEAR_CONFIGURATION_PACKET_SIZE: usize = 0x28;
pub(super) const CONMON_ROUTING_CAPACITY_PACKET_SIZE: usize = 0x28;
pub(super) const CONMON_ROUTING_CAPACITY_UNMAPPED_PREFIX_WORD_OFFSET: usize = 0x1C;
pub(super) const CONMON_ROUTING_CAPACITY_STATE_CODE_OFFSET: usize = 0x20;
pub(super) const CONMON_ROUTING_CAPACITY_UNMAPPED_WORD_OFFSET: usize = 0x22;
pub(super) const CONMON_ROUTING_CAPACITY_TRANSMIT_CHANNEL_COUNT_OFFSET: usize = 0x24;
pub(super) const CONMON_ROUTING_CAPACITY_RECEIVE_CHANNEL_COUNT_OFFSET: usize = 0x26;
pub(super) const CONMON_CURRENT_SAMPLE_RATE_OFFSET: usize = 0x24;
pub(super) const CONMON_SUPPORTED_SAMPLE_RATES_OFFSET: usize = 0x30;
pub(super) const CONMON_SUPPORTED_ENCODING_COUNT_OFFSET: usize = 0x22;
pub(super) const CONMON_CURRENT_ENCODING_OFFSET: usize = 0x24;
pub(super) const CONMON_SUPPORTED_ENCODINGS_OFFSET: usize = 0x30;
pub(super) const CONMON_SAMPLE_RATE_PULLUP_VECTOR_OFFSET_FIELD: usize = 0x20;
pub(super) const CONMON_SAMPLE_RATE_PULLUP_VECTOR_COUNT_FIELD: usize = 0x22;
pub(super) const CONMON_SAMPLE_RATE_PULLUP_APPLIED_VALUE_OFFSET: usize = 0x24;
pub(super) const CONMON_SAMPLE_RATE_PULLUP_REQUESTED_VALUE_OFFSET: usize = 0x28;
pub(super) const CONMON_SAMPLE_RATE_PULLUP_MODE_OFFSET: usize = 0x2C;
pub(super) const CONMON_SAMPLE_RATE_PULLUP_UNMAPPED_WORD_OFFSET: usize = 0x30;
pub(super) const CONMON_SAMPLE_RATE_PULLUP_VECTOR_OFFSET_BASE: usize = 0x18;
pub(super) const CONMON_SAMPLE_RATE_PULLUP_FIXED_FIELDS_END: usize = 0x34;
pub(super) const CONMON_GAIN_DIRECTION_OFFSET: usize = 0x28;
pub(super) const CONMON_GAIN_CHANNEL_COUNT_OFFSET: usize = 0x2A;
pub(super) const CONMON_GAIN_LEVELS_OFFSET: usize = 0x30;
pub(super) const CONMON_GAIN_INPUT_DIRECTION: u16 = 0x0102;
pub(super) const CONMON_GAIN_OUTPUT_DIRECTION: u16 = 0x0201;
pub(super) const CONMON_CLOCK_SOURCE_CODE_OFFSET: usize = 0x24;
pub(super) const CONMON_PREFERRED_LEADER_OFFSET: usize = 0x26;
pub(super) const CONMON_CLOCK_IDENTITY_OFFSET: usize = 0x2C;
pub(super) const CONMON_CLOCK_IDENTITY_SIZE: usize = 6;
pub(super) const CONMON_FIRST_LEADER_CLOCK_IDENTITY_OFFSET: usize = 0x32;
pub(super) const CONMON_SECOND_LEADER_CLOCK_IDENTITY_OFFSET: usize = 0x3A;
pub(super) const CONMON_LEADER_CLOCK_IDENTITY_FIELD_SIZE: usize = 8;
pub(super) const CONMON_CLOCK_SUBDOMAIN_OFFSET: usize = 88;
pub(super) const CONMON_CLOCK_SUBDOMAIN_SIZE: usize = 16;
pub(super) const CONMON_CLOCK_FREQUENCY_OFFSET_PARTS_PER_BILLION_OFFSET: usize = 0x28;
pub(super) const CONMON_CLOCK_PORT_STATE_OFFSET: usize = 0x48;
pub(super) const CONMON_CLOCK_RECORD_PAYLOAD_OFFSET: usize = 24;
pub(super) const CONMON_CLOCK_PRECEDING_COUNT_RECORD_OFFSET: usize = 44;
pub(super) const CONMON_CLOCK_PORT_DESCRIPTOR_BASE_RECORD_OFFSET: usize = 80;
pub(super) const CONMON_CLOCK_PORT_DESCRIPTOR_SIZE: usize = 4;
pub(super) const CONMON_CLOCK_PORT_HEADER_SIZE: usize = 8;
pub(super) const CONMON_CLOCK_PORT_RECORD_SIZE: usize = 16;
pub(super) const CONMON_AES67_CURRENT_NEW_OFFSET: usize = 0x21;
pub(super) const CONMON_LOCK_RESET_RECORD_OFFSET: usize = 24;
pub(super) const CONMON_LOCK_RESET_FIXED_RECORD_SIZE: usize = 24;
pub(super) const CONMON_LOCK_RESET_IDENTIFIER_WIDTH: usize = 8;
pub(super) const CONMON_EXPORT_HEADER_SIZE: usize = 28;
pub(super) const CONMON_EXPORT_DATA_OFFSET: usize = 52;
pub(super) const CONMON_INTERFACE_COUNT_OFFSET: usize = 0x20;
pub(super) const CONMON_INTERFACE_LINK_SPEED_OFFSET: usize = 0x24;
pub(super) const CONMON_INTERFACE_RECORDS_OFFSET: usize = 0x28;
pub(super) const CONMON_INTERFACE_RECORD_SIZE: usize = 20;
pub(super) const CONMON_INTERFACE_CONFIGURED_RECORD_SIZE: usize = 24;
pub(super) const CONMON_INTERFACE_CONFIGURED_RECORD_STRIDE: usize = 28;
pub(super) const CONMON_INTERFACE_REBOOT_FLAG_OFFSET: usize = 0x48;
pub(super) const CONMON_INTERFACE_PENDING_STATIC_OFFSET: usize = 0x4C;
pub(super) const CONMON_INTERFACE_MINIMUM_SIZE: usize = 0x40;

pub(super) const INTERFACE_MODE_DYNAMIC: u16 = 0x0001;
pub(super) const INTERFACE_MODE_STATIC: u16 = 0x0003;
pub(super) const INTERFACE_REBOOT_PENDING_DYNAMIC: u16 = 0x0004;
pub(super) const INTERFACE_REBOOT_PENDING_STATIC: u16 = 0x0006;
